### ISSUE TITLE
导出时报错

### ISSUE THREAD

**Issue by muermaru** [yoke88/wiznoteExporter#1]
前两个文件夹是正常的，到第三个文件夹几篇文章之后就报错了
![image](https://cloud.githubusercontent.com/assets/12495960/22676653/b28b621c-ed27-11e6-8275-62c1ee8dcab7.png)

**Comment by yoke88** [comment]
文章的标题有特殊字符么，感觉像是读文件时出问题了。

**Comment by muermaru** [comment]
我也看了下标题，但是貌似没有特殊的字符。第一次跑的话，会断在标题是'Vue.js 快速入门'的笔记前。然后再跑的话，就不按默认的顺序导出了，然后也是3篇笔记之后就报错

**Comment by yoke88** [comment]
你用的windows还是linux,那个fix函数的作用其实是修正图片及资源的引用(正常是引用网上的图片，图片下载后需要这个函数来改成本地引用)，因此如果这个函数出错，你可以把这个函数的最后两行注释掉，也或者直接把引用fix的语句注释看看

**Comment by muermaru** [comment]
注释了后面那三行之后就可以了，不过有些笔记的图片没法获取到。但是已经很不错了，多谢了~

**Comment by yoke88** [comment]
注释掉后面几行，导出的笔记引用的图片还是网上的图片，你要看看这些笔记源码中的图片连接(有可能连接用相对路径，也可能绝对路径)，反正都得转换

________________________________

**Comment by muermaru** [comment]
看了下，如果笔记里的图片引用是网络链接，导出是正常的，如果是本地的就没法显示

**Comment by muermaru** [comment]
也可能是OSX的BUG导致的？
http://stackoverflow.com/questions/11662960/ioerror-errno-22-invalid-argument-when-reading-writing-large-bytestring

**Comment by zhouyunjian** [comment]
MAC可以导出么?我试了报错un:notes yun$ /Users/yun/Documents/笔记/wiznoteExporter-master/test.py
Not Found
Traceback (most recent call last):
  File "/Users/yun/Documents/笔记/wiznoteExporter-master/test.py", line 70, in <module>
    for notebook in wiz.ls_notebooks():
  File "/Users/yun/Documents/笔记/wiznoteExporter-master/wiz/utils.py", line 54, in inner_wrap
    return _manager_func(*args, **kwargs)
  File "/Users/yun/Documents/笔记/wiznoteExporter-master/wiz/notebook.py", line 29, in ls
    result, error = self.api_request('/api/category/all')
  File "/Users/yun/Documents/笔记/wiznoteExporter-master/wiz/base.py", line 41, in api_request
    raise e.WizException(error)
wiz.e.WizException: Not Found

**Comment by yoke88** [comment]
所用API 部分已经无效
